import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/toaster';
import { TanStackProvider } from '@/providers/tanstack-query';
import AuthLayout from '@/components/auth-layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GG Store',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <TanStackProvider>
        <html lang="en">
          <body className={inter.className}>
            <AuthLayout>{children}</AuthLayout>
            <Toaster />
          </body>
        </html>
      </TanStackProvider>
    </SessionProvider>
  );
}
